spring:
  application:
    name: template
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  r2dbc:
    url: ${R2DBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    properties:
      schema: template
  flyway:
    enabled: true
    url: ${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: "0"
    schemas: template

app:
  redis:
    streams:
      test-table:
        enabled: true
        key: template:test-table-events
        poll-timeout: 1s
